<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class UserControl1
    Inherits System.Windows.Forms.UserControl

    'UserControl overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim GridViewHyperlinkColumn1 As Telerik.WinControls.UI.GridViewHyperlinkColumn = New Telerik.WinControls.UI.GridViewHyperlinkColumn()
        Dim GridViewTextBoxColumn1 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewDecimalColumn1 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn()
        Dim GridViewDecimalColumn2 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn()
        Dim GridViewTextBoxColumn2 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewSummaryItem1 As Telerik.WinControls.UI.GridViewSummaryItem = New Telerik.WinControls.UI.GridViewSummaryItem()
        Dim GridViewSummaryItem2 As Telerik.WinControls.UI.GridViewSummaryItem = New Telerik.WinControls.UI.GridViewSummaryItem()
        Dim GridViewSummaryItem3 As Telerik.WinControls.UI.GridViewSummaryItem = New Telerik.WinControls.UI.GridViewSummaryItem()
        Me.RadGridView1 = New Telerik.WinControls.UI.RadGridView()
        Me.TabeldetailharianBindingSource = New System.Windows.Forms.BindingSource(Me.components)
        Me.TokoDataSet = New Program_Penjualan_V2.tokoDataSet()
        Me.Tabel_detail_harianTableAdapter = New Program_Penjualan_V2.tokoDataSetTableAdapters.tabel_detail_harianTableAdapter()
        Me.Tabel_barang_keluarTableAdapter = New Program_Penjualan_V2.tokoDataSetTableAdapters.tabel_barang_keluarTableAdapter()
        Me.Tabel_invoice_keluarTableAdapter1 = New Program_Penjualan_V2.tokoDataSetTableAdapters.tabel_invoice_keluarTableAdapter()
        CType(Me.RadGridView1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.RadGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.TabeldetailharianBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.TokoDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'RadGridView1
        '
        Me.RadGridView1.BackColor = System.Drawing.SystemColors.Control
        Me.RadGridView1.Cursor = System.Windows.Forms.Cursors.Default
        Me.RadGridView1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.RadGridView1.Font = New System.Drawing.Font("Segoe UI", 8.25!)
        Me.RadGridView1.ForeColor = System.Drawing.SystemColors.ControlText
        Me.RadGridView1.ImeMode = System.Windows.Forms.ImeMode.NoControl
        Me.RadGridView1.Location = New System.Drawing.Point(0, 0)
        '
        'RadGridView1
        '
        Me.RadGridView1.MasterTemplate.AllowAddNewRow = False
        Me.RadGridView1.MasterTemplate.AllowColumnReorder = False
        Me.RadGridView1.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill
        GridViewHyperlinkColumn1.EnableExpressionEditor = False
        GridViewHyperlinkColumn1.FieldName = "invoice"
        GridViewHyperlinkColumn1.HeaderText = "Invoice"
        GridViewHyperlinkColumn1.IsAutoGenerated = True
        GridViewHyperlinkColumn1.Name = "invoice"
        GridViewHyperlinkColumn1.Width = 104
        GridViewTextBoxColumn1.EnableExpressionEditor = False
        GridViewTextBoxColumn1.FieldName = "nama"
        GridViewTextBoxColumn1.HeaderText = "Nama Customer"
        GridViewTextBoxColumn1.IsAutoGenerated = True
        GridViewTextBoxColumn1.Name = "nama"
        GridViewTextBoxColumn1.Width = 158
        GridViewDecimalColumn1.DataType = GetType(Double)
        GridViewDecimalColumn1.EnableExpressionEditor = False
        GridViewDecimalColumn1.FieldName = "belanja"
        GridViewDecimalColumn1.FormatString = "{0:N2}"
        GridViewDecimalColumn1.HeaderText = "Penjualan"
        GridViewDecimalColumn1.IsAutoGenerated = True
        GridViewDecimalColumn1.Name = "belanja"
        GridViewDecimalColumn1.Width = 133
        GridViewDecimalColumn2.DataType = GetType(Double)
        GridViewDecimalColumn2.EnableExpressionEditor = False
        GridViewDecimalColumn2.FieldName = "retur"
        GridViewDecimalColumn2.FormatString = "{0:N2}"
        GridViewDecimalColumn2.HeaderText = "Retur"
        GridViewDecimalColumn2.IsAutoGenerated = True
        GridViewDecimalColumn2.Name = "retur"
        GridViewDecimalColumn2.Width = 156
        GridViewTextBoxColumn2.DataType = GetType(Decimal)
        GridViewTextBoxColumn2.EnableExpressionEditor = False
        GridViewTextBoxColumn2.FieldName = "pembayaran"
        GridViewTextBoxColumn2.FormatString = "{0:N2}"
        GridViewTextBoxColumn2.HeaderText = "Pendapatan"
        GridViewTextBoxColumn2.Name = "pembayaran"
        GridViewTextBoxColumn2.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
        GridViewTextBoxColumn2.Width = 132
        Me.RadGridView1.MasterTemplate.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() {GridViewHyperlinkColumn1, GridViewTextBoxColumn1, GridViewDecimalColumn1, GridViewDecimalColumn2, GridViewTextBoxColumn2})
        Me.RadGridView1.MasterTemplate.DataSource = Me.TabeldetailharianBindingSource
        Me.RadGridView1.MasterTemplate.EnableGrouping = False
        GridViewSummaryItem1.Aggregate = Telerik.WinControls.UI.GridAggregateFunction.Sum
        GridViewSummaryItem1.FormatString = "{0:N2}"
        GridViewSummaryItem1.Name = "belanja"
        GridViewSummaryItem2.Aggregate = Telerik.WinControls.UI.GridAggregateFunction.Sum
        GridViewSummaryItem2.FormatString = "{0:N2}"
        GridViewSummaryItem2.Name = "retur"
        GridViewSummaryItem3.Aggregate = Telerik.WinControls.UI.GridAggregateFunction.Sum
        GridViewSummaryItem3.FormatString = "{0:N2}"
        GridViewSummaryItem3.Name = "pembayaran"
        Me.RadGridView1.MasterTemplate.SummaryRowsBottom.Add(New Telerik.WinControls.UI.GridViewSummaryRowItem(New Telerik.WinControls.UI.GridViewSummaryItem() {GridViewSummaryItem1, GridViewSummaryItem2, GridViewSummaryItem3}))
        Me.RadGridView1.Name = "RadGridView1"
        Me.RadGridView1.ReadOnly = True
        Me.RadGridView1.RightToLeft = System.Windows.Forms.RightToLeft.No
        Me.RadGridView1.ShowGroupPanel = False
        Me.RadGridView1.Size = New System.Drawing.Size(699, 315)
        Me.RadGridView1.TabIndex = 0
        Me.RadGridView1.Text = "RadGridView1"
        '
        'TabeldetailharianBindingSource
        '
        Me.TabeldetailharianBindingSource.DataMember = "tabel_detail_harian"
        Me.TabeldetailharianBindingSource.DataSource = Me.TokoDataSet
        '
        'TokoDataSet
        '
        Me.TokoDataSet.DataSetName = "tokoDataSet"
        Me.TokoDataSet.EnforceConstraints = False
        Me.TokoDataSet.Locale = New System.Globalization.CultureInfo("en-US")
        Me.TokoDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.ExcludeSchema
        '
        'Tabel_detail_harianTableAdapter
        '
        Me.Tabel_detail_harianTableAdapter.ClearBeforeFill = True
        '
        'Tabel_barang_keluarTableAdapter
        '
        Me.Tabel_barang_keluarTableAdapter.ClearBeforeFill = True
        '
        'Tabel_invoice_keluarTableAdapter1
        '
        Me.Tabel_invoice_keluarTableAdapter1.ClearBeforeFill = True
        '
        'UserControl1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.Controls.Add(Me.RadGridView1)
        Me.Name = "UserControl1"
        Me.Size = New System.Drawing.Size(699, 315)
        CType(Me.RadGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.RadGridView1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.TabeldetailharianBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.TokoDataSet, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

End Sub
    Friend WithEvents profit As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents RadGridView1 As Telerik.WinControls.UI.RadGridView
    Friend WithEvents TabeldetailharianBindingSource As System.Windows.Forms.BindingSource
    Friend WithEvents TokoDataSet As Program_Penjualan_V2.tokoDataSet
    Friend WithEvents Tabel_detail_harianTableAdapter As Program_Penjualan_V2.tokoDataSetTableAdapters.tabel_detail_harianTableAdapter
    Friend WithEvents Tabel_barang_keluarTableAdapter As Program_Penjualan_V2.tokoDataSetTableAdapters.tabel_barang_keluarTableAdapter
    Friend WithEvents Tabel_invoice_keluarTableAdapter1 As Program_Penjualan_V2.tokoDataSetTableAdapters.tabel_invoice_keluarTableAdapter

End Class
